지하철 노선도 & 경로 조회 미션 제출입니다.
dev-floor/kotlin-subway-path pull request #4
Opened 2021-03-01 15:32 UTC by hungry-jay

아직 경로탐색이랑 리팩토링 할곳이 많아서
금방 끝내고 말해줄테니 그때부터 리뷰해주심 감사!!

2021-03-06 16:05 UTC, lxxjn0 requested changes
우선 눈에 보이는 큰 부분들에 대해서 간단하게 피드백 남겨봤는데 한 번 확인해줘 ㅎㅅㅎ

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/app/MenuApplication.kt
> +var select: String = ""
이렇게 전역으로 변수를 사용하면 해당 변수가 thread-safe 하지 못할 것 같아.
상수도 아니고 찾아보니까 여러군데에서 사용되고 있던데 프로그램의 안정성이 떨어질 것 같은 느낌. 이 변수로 인해 의도하지 않는 동작이 일어날 확률이 클 것 같아!

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/app/LineApplication.kt
> +import subway.view.succeedRegisterLine
이건 개인적인 생각인데 view의 메서드들의 명명이 조금 일관되면 좋을 것 같아. 이름들이 뷰에서 쓰일 법한 이름이기 보다는 인스턴스 메서드나 정적 클래스 메서드에서도 있을 법한 이름 들이라 코드를 볼때 조금 헛갈리는 것 같아.

또 함수가 다 전역 범위라서 더욱 한 번에 파악하기 힘든 것 같기도 하고. 이건 근데 개인적인 생각이라 한번 참고해서 생각만 해보면 좋을 것 같아 ㅎㅅㅎ

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/app/LineApplication.kt
> +            RegisterLineService(line).register()
전체적으로 서비스 객체 사용을 보니까 하나를 만들어서 전체에서 사용하는게 아니라 매번 쓰이는 곳에서 만들어서 쓰고 버리는 것 같아. 이런 형식으로 짠 이유는 뭐야?
그리고 만약 이렇게 사용하는게 목적이었다면 오히려 클래스 메서드로 만드는게 더 효율적이지 않을까?

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
보니까 전체 코드에서 도매인 객체를 data class로 구현했던데 따로 메서드라던지 이런게 없어서 data class로 사용한 거일까?

그런데 비즈니스 로직 상으로도, 패키지에도 domain에 들어가있고 도메인 객체(엔티티성 객체)라고 생각되는데 data class로 구현하는 건 뭔가 안어울리는 느낌???
도메인 객체로 사용해야 하는데 data class로 구현하면 toString(), equals(), copy() 같은 메서드를 그대로 구현되어 있는거잖아. 도메인 객체에서 이런 메서드는 의도에 맞게 사용 유무가 선택돼야 하는데 이렇게 구현하면 그 선택권이 없게 되고 이로 인해 의도하지 않은 결과가 발생할 수도 있을 것 같아.

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/domain/dto/Path.kt
> +package subway.domain.dto
이건 dto 패키지가 아예 도메인 패키지 안에 들어가 있는데 성격이 확실하게 다른 둘이라고 생각돼서 한번 차이를 다시 확인하고 패키지를 구성해보면 좋을 것 같아.

도메인 객체가 뭔지 한 번 알아보는 것도 좋을 것 같고!!

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/repository/LineRepository.kt
> +    fun deleteByName(name: String) = lines.removeIf { it.name == name }
저장된 객체의 이름과 비교하는 부분에서 나는 Line 한테 match라는 메서드를 만들어서 구현했어. 단순히 매개변수로 전달받는 이름과 동일한 이름을 가진 Line인지 비교하는 로직인데 이렇게 짜는데 흔히 '객체에게 메시지를 보내라' 라고 하는데 이것도 한 번 찾아보면 좋을 것 같아.

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/repository/SectionRepository.kt
> +                it.downwardStation.name == downward.name
이런 로직도 여기서 해결하기보단 Section에 메서드를 구현해서 해결하면 조금 더 보기 좋고 의미를 알아차리기 좋을 것 같아

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/service/AllContentsService.kt
> +    fun getLines(): List<Any> = lineRepository.findAll().map { it.name }
이건 왜 반환 타입이 `List<Any>` 인거야??

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/service/DeleteLineService.kt
> +class DeleteLineService(val name: String) {
이건 서비스 객체의 필드로 name을 가지고 있는데 필드 변수를 이렇게 사용하는 건 잘못된 것 같아. 필드 변수는 결국 그 객체의 속성이라고 볼 수 있는데 과연 라인을 지우는 서비스의 속성으로 이름을 가지는게 맞을까?

만약 지워야하는 라인이 10개가 된다면 이 서비스를 10개 생성해야 하는걸까?

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/service/DeleteSectionService.kt
> +class DeleteSectionService(
여기도 위의 코멘트와 마찬가지야. 전체적인 서비스에서 필드를 이렇게 줬던데 이건 한번 고민해보면 좋을 것 같아

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/service/DeleteLineService.kt
> +class DeleteLineService(val name: String) {
아 추가적으로 컨트롤러 서비스같은 객체를 무상태 객체, 도메인 객체와 같은 것들을 상태 객체라고 하는데 이 키워드로 찾아보면 좀 도움이 될 것 같아

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/service/PathService.kt
> +        graph: WeightedMultigraph<String, WeightedEdge>,
여기도 graph를 상태로 가지고 있는 게 이상하지만 그걸 떠나서 이 메서드의 해당 파라미터는 불필요한 파라미터인거 같아.

2021-03-06 16:05 UTC, lxxjn0 commented on src/main/kotlin/subway/service/RegisterSectionService.kt
> +class RegisterSectionService(
서비스 객체같은 경우에 기능마다 하나씩 있는데 도메인마다 기능을 관리해주는 서비스 1개씩 두는건 어떨까?

2021-03-11 14:13 UTC, hungry-jay commented on src/main/kotlin/subway/app/MenuApplication.kt
> +var select: String = ""
동기적인 처리니까 그런거 생각안해도 될거라고 생각하긴했는데 <br>
어쨌건 어플리케이션이 여러군데에서 실행되면 select라는 변수가 thread safe하지 못한건 맞는듯 !! 👍

2021-03-11 14:16 UTC, hungry-jay commented on src/main/kotlin/subway/app/LineApplication.kt
> +import subway.view.succeedRegisterLine
흠... 이름에 대한거도 한번 쭉 고쳐야겠다라고 생각하긴했었음
특히, 주로 `get` 하는 부분에서 누구는 `get` 을 명시해주고 누구는 안해주더라고,,🤔
다른사람들 코드들 많이 보고 고민해봐야할 부분인거같아 view 부분 또한!

2021-03-11 14:41 UTC, hungry-jay commented on src/main/kotlin/subway/app/LineApplication.kt
> +            RegisterLineService(line).register()
오 클래스 메소드라는게 있는지 몰랐었네
근데 보니까 Kotlin에서는 static이 없고 companion object으로 function을 object화 하는거같더라고??
<br>
근데 클래스들의 function들을 전부 object화 해서 사용할바에
클래스 자체를 singleton처럼 object로 만들어서 사용하는 방법이 좋을거같아서 각 service들을 object로 바꿔볼 생각인데
이 점에 대해 설계를 잘못하는건 아니겠지???

2021-03-11 14:48 UTC, hungry-jay commented on src/main/kotlin/subway/app/LineApplication.kt
> +            RegisterLineService(line).register()
아 근데 생각해보니까 object로 바꾸게 되면 `init`이나 `companion object`같은걸 못쓰게 되네... 이건 불가능하겠고 다른방법을 생각해봐야겠다 ㅠ

2021-03-11 15:04 UTC, hungry-jay commented on src/main/kotlin/subway/service/AllContentsService.kt
> +    fun getLines(): List<Any> = lineRepository.findAll().map { it.name }
여긴 원래는 getLines에서 `findAll()`을 통해 모든 `line`들을 반환하게 해서 
view에서 `lines.map { print(it.name) }` 이런식으로 맵핑하려했었어
근데 이렇게 하려면 view 입장에서도 line이라는 class가 어떻게 생겼는지도 알아야 하고 그걸 없애려고 이름만 전달하도록 저렇게 뽑았었엉
`List<String>` 으로 바꾸는게 더 명확할거같다 !

2021-03-11 15:16 UTC, hungry-jay commented on src/main/kotlin/subway/app/LineApplication.kt
> +            RegisterLineService(line).register()
근데 생각해보니까 애초에 설계자체를
기능을 하나 수행하려 할 때마다 service 객체를 새로 만들어 제약사항에 어긋나지 않는지 확인하려고 저렇게 짠거같아
그러니까 내 설계방식은 애초에 각각의 수행할 "기능"들에 초점을 두고,
그걸 하나의 service라고 두어 각각의 서비스가 당연하게도 하나의 상태객체인거로 생각한거지.

근데 저번에 얘기했듯이 service나 controller, repository이거는 각각이 하나의 싱글톤(혹은 Bean?)인 무상태객체인게 맞는거지?

2021-03-11 15:29 UTC, hungry-jay commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
정보 저장용 클래스라는 점에 Entity는 당연히 data class가 되어야한다고 생각했는데
많은 곳에서 jpa를 사용할떄의 문제같은거 때문에 Entity를 data class로 사용하지 않는걸 추천하네..

그럼 혹시 domain(entity)라고 생각했을때 domain을 data class로 선언하는건 개념적으로 맞는걸까?

2021-03-11 15:31 UTC, hungry-jay commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
real world 하면서 model, controller, service 이렇게 약간 mvc?스럽게 설계한게 떠올라서
아마 저걸 model과 결이 같은거라고 생각한거같은데 둘은 다르다고 봐야하는건가?

2021-03-11 15:35 UTC, hungry-jay commented on src/main/kotlin/subway/domain/dto/Path.kt
> +package subway.domain.dto
이것도 위의 질문이랑 같은게, realworld에서 model 내부에 DTO 패키지를 만든거로 기억하는데 !
그 편이 자연스럽다고 생각한 이유는 DTO이든 일반 domain이든 정해져있는 하나의 model? 같은 느낌이라고 생각해서 그렇게 구성했었어 ! 이렇게 생각한거 자체가 어떠한 관점에서 틀린방향 인건지 조언좀 부탁해,,,,

2021-03-11 15:39 UTC, hungry-jay commented on src/main/kotlin/subway/service/RegisterSectionService.kt
> +class RegisterSectionService(
이 부분은 사실 원래는 그렇게 설계했었는데, README 요구사항 봤을 때
Station, Line은 각각 하나씩인데 Section은 기능별로 요구사항을 나눠놨어서 Section만 나눠놨다가 ㅠ(왜냐면 붙이면 너무 코드가 길어지고 복잡해지는거같아서 가독성때메)
일관성 유지하려고 전부다 하나씩 나눠놓은거거든!
근데 사람마다 다르겠지만 다들 대개는 1도메인 : 1서비스로 설계하는게 일반적인건가!?

혹시 그러한 구현을 통해 얻을 수 있는 이점같은것도있나???🤔

2021-03-12 08:39 UTC, hungry-jay commented on src/main/kotlin/subway/service/PathService.kt
> +        graph: WeightedMultigraph<String, WeightedEdge>,
이부분은 리팩토링하다가 깜빡하고 안지우고 걍 뒀나보다..ㅜ

2021-03-13 06:01 UTC, hungry-jay commented on src/main/kotlin/subway/repository/LineRepository.kt
> +    fun deleteByName(name: String) = lines.removeIf { it.name == name }
디미터 법칙이란거랑 관련된거구나,, 우테코에서 작성해놓은 글 읽고 드디어 이해했다 ㅋㅋㅋ..

1. https://woowacourse.github.io/javable/post/2020-04-28-ask-instead-of-getter/
2. https://johngrib.github.io/wiki/law-of-demeter/#%EB%94%94%EB%AF%B8%ED%84%B0-%EB%B2%95%EC%B9%99%EC%9D%84-%EC%9C%84%EB%B0%98%ED%95%9C-%EC%BD%94%EB%93%9C---%EA%B8%B0%EC%B0%A8-%EC%B6%A9%EB%8F%8C

2021-03-13 06:01 UTC, hungry-jay commented on src/main/kotlin/subway/repository/SectionRepository.kt
> +                it.downwardStation.name == downward.name
222222

2021-03-13 06:06 UTC, hungry-jay commented on src/main/kotlin/subway/repository/LineRepository.kt
> +    fun deleteByName(name: String) = lines.removeIf { it.name == name }
1번 글에도 나와있는데
racingCar 프로젝트같은 경우에 cars에서 car.position을 비교해 winner를 구하는것 또한 디미터 법칙이라는 관점에서 보면 잘못된거네. 저 관점에서 보면 car의 private한 상태니까 본인(car)의 position과 또다른 인스턴스 car의 position을 비교하는 행위는 철저히 car에서 해야하는게 맞는건가보다.. 내가 생각한게 맞는건가!?

2021-03-13 06:54 UTC, hungry-jay commented on src/main/kotlin/subway/repository/LineRepository.kt
> +    fun deleteByName(name: String) = lines.removeIf { it.name == name }
여기서 배운거 section에도 적용했는데 일단 모양새자체는 좋아진거같은데
메서드명 수정하다보니까 메서드 이름 가독성은 개 똥망됐다 ㅋㅋ ㅠ
`existsByLineNameAndDownwardName()` ㅠ

2021-03-13 07:00 UTC, hungry-jay commented on src/main/kotlin/subway/service/DeleteLineService.kt
> +class DeleteLineService(val name: String) {
굿굿 !
근데 어느 경우에도 서비스는 무상태 객체가 되는게 맞는거지? 
때에따라 서비스가 달라질수있는게 아니라 항상 서비스라는건 유일해야하는게 맞는거면 
위에 물어본 질문이 해결될거같다
https://github.com/dev-floor/kotlin-subway-path/pull/4#discussion_r592446688
이거!

2021-03-13 07:01 UTC, hungry-jay commented on src/main/kotlin/subway/service/DeleteSectionService.kt
> +class DeleteSectionService(
👍👍👍👍

2021-03-13 07:48 UTC, hungry-jay commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
> 그럼 혹시 domain(entity)라고 생각했을때 domain을 data class로 선언하는건 개념적으로 맞는걸까?

다시보니까 이게 살짝 말이 좀 이상하네 ㅋㅋ 어쨌건
`Data class == 데이터를 저장(혹은 보관?)만을 위한 클래스` 이고,
우리가 사용하는 domain은 단순히 정보 저장용 뿐은 아니기 때문에 data class가 될 수 없다라고 이해하면 될까?

2021-03-13 07:48 UTC, hungry-jay commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
> real world 하면서 model, controller, service 이렇게 약간 mvc?스럽게 설계한게 떠올라서
> 아마 저걸 model과 결이 같은거라고 생각한거같은데 둘은 다르다고 봐야하는건가?

이거때문에 조금 헷갈리네 ㅠ

2021-03-13 08:17 UTC, hungry-jay commented on src/main/kotlin/subway/app/LineApplication.kt
> +import subway.view.succeedRegisterLine
view에 대한건 반영완료했는데
getLine() 이런거 뭔가 바꿔주고싶다 어떤방법이 좋을까 ??? ㅇ.ㅇ

2021-03-13 11:11 UTC, hungry-jay commented on src/main/kotlin/subway/service/RegisterSectionService.kt
> +class RegisterSectionService(
이 부분도 다시생각해봤는데 분리함으로써 얻을수 있는 이점은 있는거같긴해
예를들어 registerStation, deleteStation을 따로 구현했을 때 각각의 기능을 위한 제약사항을
각 service객체 생성 시점에 검사할수있다는거??

근데 만약 `service는 항상 무상태객체 여야한다.`라고 한다면 service는 단 한번만 초기화할테니 그러한 경우에는 init이 아닌 다른 방법으로 초기화를해야할테고 그럴 땐 아마 둘이 합치는게 더 보기 좋을수도 있을거같음!!

2021-03-13 13:13 UTC, lxxjn0 commented on src/main/kotlin/subway/app/LineApplication.kt
> +import subway.view.succeedRegisterLine
나도 이건 좀 어렵긴 하더라.. getter에 이름을 다르게 붙이는 것도 어렵기도 하고.. 이건 그냥 본인의 코드에서 일관성있게 작성하면 될 듯? 코드를 읽을 때 '아 이 이름의 메서드는 이런 역할을 하는구나'하고 파악할 수 있도록?

2021-03-13 13:17 UTC, lxxjn0 commented on src/main/kotlin/subway/app/LineApplication.kt
> +            RegisterLineService(line).register()
맞어 도메인 별로 하나의 서비스를 두고 거기서 여러 기능들을 구현하도록? 싱글톤으로 만들어서 사용하면 될 듯?

2021-03-13 13:35 UTC, lxxjn0 commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
일단 entity가 단순한 정보 저장용 클래스는 전혀 아니라고 생각해. 

data class는 VO, 값 객체를 사용하는 방법이라고 난 알고 있거든. 우리가 int, long 이런걸 **값**으로 사용하는데 객체를 이런 형식(값)으로 사용하려고 하는게 이런걸 VO라고 하고 이걸 data class로 사용하면 구현하기 편하지. 왜냐면 값은 동등 비교를 하는거거든.

Long 값이 1인 변수가 2개가 있다고 하면 객체 입장에서는 두 개는 다른 인스턴스로 생성되지만 값으로 비교하면 동일한 값이잖아. 객체간의 동일성 비교는 ==을, 동등성 비교는 equals를 사용하거든. data class는 equals를 지원해주기 때문에 동등성 비교가 가능하고 이는 값의 비교가 가능하다고 볼 수 있어. 내가 말을 조금 어렵게 하긴 했는데 다음에 만나면 말해줄게 ㅋㅋㅋㅋ

그럼 여튼 data class는 동등성 비교를 하는데 그럼 과연 entity가 동등성 비교를 하는 게 맞을까? 만약 DB에

|상품 이름|가격|날짜|
|:---:|:---:|:---:|
|A|1000|210313|
|B|3000|210313|
|A|1000|210313|

이런 데이터가 저장되어 있다고 치자. 만약 entity가 data class라면 첫 번째 row와 세 번째 row는 equals 비교를 하면 동일하다고 할거야. 가지고 있는 내부 값이 모두 동일하니까? 그런데 데이터 관점에서 과연 두 개는 같다고 말할 수 있을까? 아예 각각 다른 행에 저장이 되었는데?

이것처럼 비즈니스 요구사항으로 '내부 값이 같으면 같다'라는 조건이 있다면 equals를 선택하는 거지 이게 default로 구현되어 있는 건 잘못됐다고 생각해. 그런 관점에선 data class를 entity 구현으로 사용하는 건 아니라고 생각해.

이건 entity, domain, vo, dto 등 용어들에 대해서 이해하고 쓰는게 좋을 것 같아서 한 번 찾아보고 공부하면 좋을 것 같어

2021-03-13 14:20 UTC, lxxjn0 commented on src/main/kotlin/subway/domain/dto/Path.kt
> +package subway.domain.dto
- [DAO, DTO, Entity class의 차이](https://gmlwjd9405.github.io/2018/12/25/difference-dao-dto-entity.html)
- [DTO의 사용 범위에 대하여](https://xlffm3.github.io/spring%20&%20spring%20boot/DTOLayer/)
- [DTO 프로젝트 위치 관련](https://www.inflearn.com/questions/24222)

우선 이 글들을 한번 보면 좋을 것 같아.

2021-03-13 14:51 UTC, lxxjn0 commented on src/main/kotlin/subway/repository/LineRepository.kt
> +    fun deleteByName(name: String) = lines.removeIf { it.name == name }
ㅋㅋㅋㅋ 이름은 사실 나도 아직 어려워서..ㅋㅋㅋ 이건 일단 의미에 맞게 작성하고 간략하게 할 수 있으면 하는게 좋은 것 같어 ㅋㅋㅋ

2021-03-13 15:11 UTC, lxxjn0 commented on src/main/kotlin/subway/service/RegisterSectionService.kt
> +class RegisterSectionService(
저번에 말한 것처럼 서비스를 생성할 때 제약사항을 검사한다? 그러면 매번 해당 기능을 사용할 때마다 서비스를 생성하는 거잖아. 

만약 사용자가 역을 100번 등록하면 100개의 서비스를 생성하고 반환하고 하는건 너무 비용이 크지 않을까? 실질적으로 역을 등록할 때 실행하는 비즈니스 로직은 항상 동일한데 단지 생성하는 역의 이름이 바뀐다고 매번 서비스 객체를 생성해야 한다? 
그것보다는 하나를 생성하고 매번 역의 이름을 전달받아서 하나의 객체가 메서드를 100번 실행하는 게 더 좋지 않을까? 그러면 이 방법으로 99번의 생성횟수가 줄어들잖아.

그리고 만약 매번 많은 객체를 생성,반환하면 그만큼 gc가 자주 불릴건데 이것도 성능에 안좋은 영향을 미칠 거고.

등록과 삭제 작업에 대한 서비스 코드를 분리할 수 있다고 생각해. 그런데 해당 코드가 몇 백줄이 넘지 않은 이상 굳이 분리를 해야하나싶어.
또 서비스를 분리할 때는 주로 사용하는 의존성이 다를 때 분리하기도 하더라고. 만약 등록, 수정, 삭제에서는 2개의 레퍼지토리와 1개의 서비스를 가져와 쓰는데 조회에서는 1개의 레퍼지토리만 사용한다? 이런 경우에는 분리해서 구현할 수도 있지. 이게 내가 알기로 도메인 서비스, 응용 서비스의 차이로 알고 있는데 나도 이 부분은 정확히 공부를 안해봐서 잘은 모르겠어..

그래서 형이 질문했던 부분에서

1. 코드의 가독성 부분에서 분리하는 게 어떨까?
  - 코드가 길어진다는 부분에서는 몇백줄이 넘는 코드가 아닌 이상 굳이 분리해야하나 싶어. 근데 이 부분은 개인의 생각 차이라서 뭐 각자의 선택이지 않을까 싶어.
    - 그런데 여기선 CRUD 1개씩 밖에 없어서 4개지만 비즈니스 로직이 많아서 만약 10개의 기능이 필요하다면 10개의 서비스를 만든다? 그것보다는 연관된 도메인이 수행해야 하는 기능을 모아두는 개념으로 서비스를 구현하면 더 응집도 있고 좋지 않을까 생각해.
    - 이런 관점에서 도메인 당 1개의 서비스가 나왔지 않았을까? 이것도 물론 나의 생각!
2. 생성하는 시점에서 유효성을 검사할 수 있다?
  - 이건 가지는 이점보다 손실이 더 큰거 같아. 기능을 한 개의 메서드로 정의하고 메서드를 실행할 때 유효성을 검사해도 1개의 기능을 실행할 때 1개의 유효성을 검증하는 거라서 난 딱히 장점을 가질 수는 없다고 생각해.
  - 객체는 최대한 자주 생성하는 건 안 좋은 것 같아. 매번 생성하고 생성한 객체에 대한 참조가 사라질 때 마다 gc에서 추적하고 관리해야 하는 비용도 들고 동일한 기능을 하는 객체를 사용 시점마다 매번 재생성 하는 건 불필요한 객체 생성으로 느껴져서?

2021-03-17 14:17 UTC, hungry-jay commented on src/main/kotlin/subway/domain/Line.kt
> +data class Line(val name: String) {
VO 자체만을 봤을땐 전혀 이해가 안 됐었는데 너가 data class를 VO라고 설명해주니까 직관적으로 (조금은)이해되긴 하네,,
많은곳에서 DTO 는 VO와 거의같다 라고 이야기하는데 그 차이점도 뭔가 이해되는거같아 ㅋㄷ

언급한 동일성 비교, 동등성 비교는 살짝 자스에서도 비슷한개념이 있었던거같아서 확 이해되긴 하고
그 밑에서 언급한 예시도 이해하기엔 너무 좋은 예시같아

근데 사실 아무리 글을 읽어도 솔직히 내가 경험해보지 않은이상 명확한 차이를 구분짓는데에는 한계가 있구나 라고 생각한게,, ㅋㅋㅋㅋ
아무리 찾아보고 해 어떻게 쓰이는지를 명확하게 정리한 글을 못보기도했고,, 일단은 내 경험의 부재가 큰듯.. 너가 잘설명해준것도 있는데 내가 명확하게 이해하려면 실제 프로젝트를 하면서 느껴봐야할거같음ㅋㅋㅋ,, 하아 힘들고나

2021-03-17 15:26 UTC, hungry-jay commented on src/main/kotlin/subway/app/LineApplication.kt
> +import subway.view.succeedRegisterLine
일단 view에 대한건 별로 신경쓰지 않기로 했지만 다 바꾸긴했는데,,

2021-03-23 01:24 UTC, hungryjayy commented on src/main/kotlin/subway/app/LineApplication.kt
> +            RegisterLineService(line).register()
반영완료 !

2021-03-23 02:14 UTC, hungry-jay commented on src/main/kotlin/subway/domain/dto/Path.kt
> +package subway.domain.dto
너 글 참고하고서, 지금 내 플젝에서는 controller와 service 모두 DTO를 필요로 할것같은데 어디다 둬야될까 고민하다가 
https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md
이 글 봤는데 이것도 도움되는것같다 ! 일단은 둘다에서 사용가능하도록 구성해야할듯

2021-03-23 08:06 UTC, hungry-jay commented on src/main/kotlin/subway/service/RegisterSectionService.kt
> +class RegisterSectionService(
> 저번에 말한 것처럼 서비스를 생성할 때 제약사항을 검사한다? 그러면 매번 해당 기능을 사용할 때마다 서비스를 생성하는 거잖아.
> 
> 만약 사용자가 역을 100번 등록하면 100개의 서비스를 생성하고 반환하고 하는건 너무 비용이 크지 않을까? 실질적으로 역을 등록할 때 실행하는 비즈니스 로직은 항상 동일한데 단지 생성하는 역의 이름이 바뀐다고 매번 서비스 객체를 생성해야 한다?
> 그것보다는 하나를 생성하고 매번 역의 이름을 전달받아서 하나의 객체가 메서드를 100번 실행하는 게 더 좋지 않을까? 그러면 이 방법으로 99번의 생성횟수가 줄어들잖아.
> 
> 그리고 만약 매번 많은 객체를 생성,반환하면 그만큼 gc가 자주 불릴건데 이것도 성능에 안좋은 영향을 미칠 거고.

GC 관점에서도, 개념적으로도 Repo, Service 얘네는 싱글턴으로 되어야하는게 맞는듯 ! 반영했음

2021-03-23 08:14 UTC, hungry-jay commented on src/main/kotlin/subway/service/RegisterSectionService.kt
> +class RegisterSectionService(
> 등록과 삭제 작업에 대한 서비스 코드를 분리할 수 있다고 생각해. 그런데 해당 코드가 몇 백줄이 넘지 않은 이상 굳이 분리를 해야하나싶어.
> 또 서비스를 분리할 때는 주로 사용하는 의존성이 다를 때 분리하기도 하더라고. 만약 등록, 수정, 삭제에서는 2개의 레퍼지토리와 1개의 서비스를 가져와 쓰는데 조회에서는 1개의 레퍼지토리만 사용한다? 이런 경우에는 분리해서 구현할 수도 있지. 이게 내가 알기로 도메인 서비스, 응용 서비스의 차이로 알고 있는데 나도 이 부분은 정확히 공부를 안해봐서 잘은 모르겠어..
> 
> 그래서 형이 질문했던 부분에서
> 
> 1. 코드의 가독성 부분에서 분리하는 게 어떨까?
> 
> * 코드가 길어진다는 부분에서는 몇백줄이 넘는 코드가 아닌 이상 굳이 분리해야하나 싶어. 근데 이 부분은 개인의 생각 차이라서 뭐 각자의 선택이지 않을까 싶어.
>   
>   * 그런데 여기선 CRUD 1개씩 밖에 없어서 4개지만 비즈니스 로직이 많아서 만약 10개의 기능이 필요하다면 10개의 서비스를 만든다? 그것보다는 연관된 도메인이 수행해야 하는 기능을 모아두는 개념으로 서비스를 구현하면 더 응집도 있고 좋지 않을까 생각해.
>   * 이런 관점에서 도메인 당 1개의 서비스가 나왔지 않았을까? 이것도 물론 나의 생각!

이 부분에 대해서도 `연관된 도메인이 수행해야 하는 기능을 모아두는 개념으로 서비스를 구현하면 더 응집도 있고 좋지 않을까 생각해.` 이 관점에서 봤을때 뭔가 서비스를 기능단위로 나누는건 의미가 없다고 생각이 드네,,
사실 subway-path같은 경우 조금 자명하긴 한데, 복잡한 프로젝트같은 경우에 `응집도` 측면에서 깊게 생각해봐야 하나..?? 사내 서버코드만 봐도 1 handler : 1 service 이긴 하거든.
이거를 위반해야 하는 경우가 궁금하네

2021-06-18 01:31 UTC, closed without merging